### ISSUE TITLE
MD versie tweaken

### ISSUE THREAD

**Issue by frankmeeuwsen** [frankmeeuwsen/Bloghelden#2]
De Markdown versie van het ebook is een directe port van de doc versie. Deze moet nog worden nagekeken op breaks, links en doorloop van de tekst.

**Comment by ghost** [comment]
Wat is je eerste indruk: zijn er veel correcties nodig of valt het mee?

**Comment by frankmeeuwsen** [comment]
Ik heb er nog niet in detail naar gekeken. Ik denk dat het vooral in de
opmaak zit om de boel leesbaar te maken.

Met vriendelijke groet,

Frank Meeuwsen
The Incredible Adventure starts here... http://www.incredibleadventure.nl/

/frankmeeuwsen http://www.twitter.com/frankmeeuwsen
/frankmeeuwsen http://www.linkedin.com/in/frankmeeuwsen

Alles over Evernote Business vind je op http://allesonthouden.nl
